// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zCg487VPs5NyC5Di1DQKM3g0Q2SRmIk',
    appId: '1:738967451070:web:a785a2fdd79a257852b5ef',
    messagingSenderId: '738967451070',
    projectId: 'chatsapp-8e056',
    authDomain: 'chatsapp-8e056.firebaseapp.com',
    storageBucket: 'chatsapp-8e056.appspot.com',
    measurementId: 'G-5D7DSLZG4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuu7Koy2BJgSguiv4lfNOJI6qWtZOSKnM',
    appId: '1:738967451070:android:fc2f1b1bbd0dd60c52b5ef',
    messagingSenderId: '738967451070',
    projectId: 'chatsapp-8e056',
    storageBucket: 'chatsapp-8e056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh1hzHz72vfJqUKvMf77vvuTsRGilDhNU',
    appId: '1:738967451070:ios:cb201901e6e4d21052b5ef',
    messagingSenderId: '738967451070',
    projectId: 'chatsapp-8e056',
    storageBucket: 'chatsapp-8e056.appspot.com',
    iosClientId: '738967451070-1bclts7c3au69v1in8mn6kgl2o182uom.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmediaapp',
  );
}
